[2023-10-09 02:42:13,089 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:42:13,090 : ERROR : main : [Errno 2] No such file or directory: '..\\config\\config.yaml']
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise e
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '..\\config\\config.yaml'
[2023-10-09 02:43:44,127 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:43:44,127 : ERROR : main : [Errno 2] No such file or directory: '..\\..\\..\\config\\config.yaml']
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise e
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\..\\config\\config.yaml'
[2023-10-09 02:44:54,310 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:44:54,311 : ERROR : main : [Errno 2] No such file or directory: '..\\..\\config\\config.yaml']
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise e
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\config\\config.yaml'
[2023-10-09 02:47:47,391 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:47:47,391 : ERROR : main : [Errno 2] No such file or directory: '\\config\\config.yaml']
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise e
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '\\config\\config.yaml'
[2023-10-09 02:48:03,042 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:48:03,042 : ERROR : main : [Errno 2] No such file or directory: '..\\config\\config.yaml']
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise e
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\utils\common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '..\\config\\config.yaml'
[2023-10-09 02:48:20,020 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:48:20,021 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-10-09 02:48:20,022 : INFO : common : created directory at: artifacts]
[2023-10-09 02:48:20,022 : INFO : common : created directory at: ../artifacts/data_ingestion]
[2023-10-09 02:49:35,802 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-10-09 02:49:39,790 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-10-09 02:49:39,791 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-09 02:50:57,409 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-09 02:50:57,410 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-10-09 02:50:57,410 : INFO : common : created directory at: artifacts]
[2023-10-09 02:50:57,411 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-10-09 02:52:18,167 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-10-09 02:52:22,669 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-10-09 02:52:22,671 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-12 01:43:59,664 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-10-12 01:43:59,666 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-10-12 01:43:59,669 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-10-12 01:43:59,669 : INFO : common : created directory at: artifacts]
[2023-10-12 01:43:59,670 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-10-12 01:44:00,020 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-10-12 01:44:00,020 : INFO : data_ingestion : there is some error while extracting the files]
[2023-10-12 01:44:00,021 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-10-12 01:44:00,021 : INFO : main : ***********************]
[2023-10-12 01:44:00,021 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-10-12 01:44:00,022 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-10-12 01:44:00,023 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-10-12 01:44:00,023 : INFO : common : created directory at: artifacts]
[2023-10-12 01:44:00,023 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-10-12 01:44:02,288 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-12 01:44:03,047 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-10-12 01:44:03,584 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-10-12 01:44:03,790 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-11-14 14:55:06,519 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 14:55:06,521 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-11-14 14:55:06,522 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-11-14 14:55:06,523 : INFO : common : created directory at: artifacts]
[2023-11-14 14:55:06,523 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-11-14 14:55:06,523 : ERROR : main : Argument path of type <class 'str'> to <function get_size at 0x000001ACFF95A1F0> does not match annotation type <class 'pathlib.Path'>]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 30, in download_file
    logger.info(f"The file is already exists of size : {get_size(data_name)}")
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 845, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path of type <class 'str'> to <function get_size at 0x000001ACFF95A1F0> does not match annotation type <class 'pathlib.Path'>
[2023-11-14 14:56:48,120 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 14:56:48,121 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-11-14 14:56:48,122 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-11-14 14:56:48,123 : INFO : common : created directory at: artifacts]
[2023-11-14 14:56:48,123 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-11-14 14:59:09,666 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-11-14 14:59:13,934 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-11-14 14:59:13,936 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 14:59:13,936 : INFO : main : ***********************]
[2023-11-14 14:59:13,936 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-11-14 14:59:13,938 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-11-14 14:59:13,939 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-11-14 14:59:13,939 : INFO : common : created directory at: artifacts]
[2023-11-14 14:59:13,941 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-11-14 14:59:20,065 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 14:59:20,929 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-11-14 14:59:21,322 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-11-14 14:59:21,469 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-01 17:50:50,217 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 17:50:50,219 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:50:50,220 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:50:50,221 : INFO : common : created directory at: artifacts]
[2023-12-01 17:50:50,221 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 17:50:50,871 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-01 17:50:50,871 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-01 17:50:50,871 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-01 17:50:50,871 : INFO : main : ***********************]
[2023-12-01 17:50:50,871 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-01 17:50:50,873 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:50:50,874 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:50:50,874 : INFO : common : created directory at: artifacts]
[2023-12-01 17:50:50,875 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-01 17:50:56,116 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 17:50:56,813 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-01 17:50:57,273 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-01 17:50:57,427 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-01 17:53:35,224 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 17:53:35,228 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:53:35,229 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:53:35,229 : INFO : common : created directory at: artifacts]
[2023-12-01 17:53:35,229 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 17:53:35,511 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-01 17:53:35,511 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-01 17:53:35,511 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-01 17:53:35,512 : INFO : main : ***********************]
[2023-12-01 17:53:35,512 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-01 17:53:35,514 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:53:35,515 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:53:35,515 : INFO : common : created directory at: artifacts]
[2023-12-01 17:53:35,515 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-01 17:53:36,619 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 17:53:37,325 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-01 17:53:37,785 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-01 17:53:37,930 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-01 17:55:45,929 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 17:55:45,932 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:55:45,933 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:55:45,933 : INFO : common : created directory at: artifacts]
[2023-12-01 17:55:45,933 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 17:55:46,188 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-01 17:55:46,188 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-01 17:55:46,189 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-01 17:55:46,189 : INFO : main : ***********************]
[2023-12-01 17:55:46,189 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-01 17:55:46,191 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:55:46,192 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:55:46,192 : INFO : common : created directory at: artifacts]
[2023-12-01 17:55:46,192 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-01 17:55:46,952 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 17:55:47,650 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-01 17:55:48,104 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-01 17:55:48,275 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-01 17:56:09,619 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 17:56:09,621 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:56:09,622 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:56:09,622 : INFO : common : created directory at: artifacts]
[2023-12-01 17:56:09,622 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 17:56:09,871 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-01 17:56:09,871 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-01 17:56:09,872 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-01 17:56:09,872 : INFO : main : ***********************]
[2023-12-01 17:56:09,872 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-01 17:56:09,874 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 17:56:09,875 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 17:56:09,875 : INFO : common : created directory at: artifacts]
[2023-12-01 17:56:09,876 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-01 17:56:10,657 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 17:56:11,342 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-01 17:56:11,803 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-01 17:56:11,964 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-01 18:08:36,449 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 18:08:36,452 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 18:08:36,453 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 18:08:36,453 : INFO : common : created directory at: artifacts]
[2023-12-01 18:08:36,453 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 18:09:52,423 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-01 18:09:56,902 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-01 18:09:56,903 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-01 18:09:56,904 : INFO : main : ***********************]
[2023-12-01 18:09:56,904 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-01 18:09:56,906 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 18:09:56,907 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 18:09:56,907 : INFO : common : created directory at: artifacts]
[2023-12-01 18:09:56,907 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-01 18:09:57,749 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 18:09:58,621 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-01 18:09:59,045 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-01 18:09:59,234 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-01 19:42:09,331 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 19:42:09,334 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:42:09,334 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 19:42:09,335 : INFO : common : created directory at: artifacts]
[2023-12-01 19:42:09,335 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 19:42:09,335 : ERROR : main : Argument path of type <class 'str'> to <function get_size at 0x00000133FF90A1F0> does not match annotation type <class 'pathlib.Path'>]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 34, in download_file
    logger.info(f"The file is already exists of size : {get_size(data_name)}")
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 845, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path of type <class 'str'> to <function get_size at 0x00000133FF90A1F0> does not match annotation type <class 'pathlib.Path'>
[2023-12-01 19:44:54,620 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 19:44:54,622 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:44:54,623 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 19:44:54,623 : INFO : common : created directory at: artifacts]
[2023-12-01 19:44:54,624 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 19:44:54,624 : ERROR : main : Argument path of type <class 'str'> to <function get_size at 0x0000020ADDF1A1F0> does not match annotation type <class 'pathlib.Path'>]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 34, in download_file
    logger.info(f"The file is already exists of size : {get_size(data_name)}")
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 845, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path of type <class 'str'> to <function get_size at 0x0000020ADDF1A1F0> does not match annotation type <class 'pathlib.Path'>
[2023-12-01 19:47:31,447 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 19:47:31,449 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:47:31,450 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 19:47:31,451 : INFO : common : created directory at: artifacts]
[2023-12-01 19:47:31,451 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 19:48:50,133 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-01 19:48:59,246 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-01 19:48:59,266 : ERROR : main : listdir: path should be string, bytes, os.PathLike or None, not DataIngestion]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 20, in main
    data_ingestion.process_data()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 50, in process_data
    for l in tqdm(os.listdir(images_des)):
TypeError: listdir: path should be string, bytes, os.PathLike or None, not DataIngestion
[2023-12-01 19:55:58,244 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 19:55:58,260 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:55:58,260 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 19:55:58,260 : INFO : common : created directory at: artifacts]
[2023-12-01 19:55:58,260 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 19:55:58,265 : ERROR : main : Argument path of type <class 'str'> to <function get_size at 0x00000298FD0B91F0> does not match annotation type <class 'pathlib.Path'>]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 11, in <module>
    data_ingestion.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 34, in download_file
    logger.info(f"The file is already exists of size : {get_size(data_name)}")
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\ensure\main.py", line 845, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path of type <class 'str'> to <function get_size at 0x00000298FD0B91F0> does not match annotation type <class 'pathlib.Path'>
[2023-12-01 19:57:36,996 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-01 19:57:37,011 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:57:37,011 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 19:57:37,011 : INFO : common : created directory at: artifacts]
[2023-12-01 19:57:37,011 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-01 19:57:37,011 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-01 19:57:43,665 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-01 19:57:56,217 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-01 19:57:56,217 : INFO : main : ***********************]
[2023-12-01 19:57:56,217 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-01 19:57:56,217 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-01 19:57:56,232 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-01 19:57:56,232 : INFO : common : created directory at: artifacts]
[2023-12-01 19:57:56,232 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-01 19:57:56,943 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-01 19:57:58,706 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-01 19:57:59,487 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-01 19:57:59,738 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-03 17:38:11,691 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:38:11,694 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:38:11,695 : INFO : common : created directory at: artifacts]
[2023-12-03 17:38:11,697 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:38:11,698 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:38:11,699 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:39:28,186 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:39:28,188 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:39:28,189 : INFO : common : created directory at: artifacts]
[2023-12-03 17:39:28,190 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:39:28,190 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:39:28,191 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:40:26,062 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:40:26,064 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:40:26,065 : INFO : common : created directory at: artifacts]
[2023-12-03 17:40:26,066 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:40:26,067 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:40:26,068 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:41:08,470 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:41:08,472 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:41:08,474 : INFO : common : created directory at: artifacts]
[2023-12-03 17:41:08,474 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:41:08,475 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:41:08,476 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:43:47,808 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:43:47,810 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:43:47,811 : INFO : common : created directory at: artifacts]
[2023-12-03 17:43:47,812 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:43:47,813 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:43:47,814 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:45:24,503 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:45:24,505 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:45:24,507 : INFO : common : created directory at: artifacts]
[2023-12-03 17:45:24,507 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:45:24,508 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:45:24,509 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:47:23,586 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:47:23,588 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:47:23,589 : INFO : common : created directory at: artifacts]
[2023-12-03 17:47:23,589 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:47:23,590 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:47:23,591 : INFO : common : created directory at: artifacts\training]
[2023-12-03 17:50:50,309 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-03 17:50:50,312 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:50:50,313 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:50:50,313 : INFO : common : created directory at: artifacts]
[2023-12-03 17:50:50,313 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-03 17:50:50,314 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-03 17:50:54,847 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-03 17:50:57,716 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-03 17:50:57,717 : INFO : main : ***********************]
[2023-12-03 17:50:57,717 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-03 17:50:57,720 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:50:57,722 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:50:57,722 : INFO : common : created directory at: artifacts]
[2023-12-03 17:50:57,722 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-03 17:51:00,644 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-03 17:51:01,515 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-03 17:51:01,910 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-03 17:51:02,085 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-03 17:52:00,709 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 17:52:00,711 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 17:52:00,712 : INFO : common : created directory at: artifacts]
[2023-12-03 17:52:00,713 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 17:52:00,714 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 17:52:00,715 : INFO : common : created directory at: artifacts\training]
[2023-12-03 18:40:31,127 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-03 18:40:31,130 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 18:40:31,131 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 18:40:31,131 : INFO : common : created directory at: artifacts]
[2023-12-03 18:40:31,132 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-03 18:41:49,710 : INFO : data_ingestion : allandclive/chicken-disease-1 downloaded ! ]
[2023-12-03 18:41:54,590 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-03 18:42:00,149 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-03 18:42:00,149 : INFO : main : ***********************]
[2023-12-03 18:42:00,149 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-03 18:42:00,151 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 18:42:00,152 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 18:42:00,152 : INFO : common : created directory at: artifacts]
[2023-12-03 18:42:00,153 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-03 18:42:04,453 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-03 18:42:05,347 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-03 18:42:05,874 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-03 18:42:06,047 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-03 18:42:06,047 : INFO : main : ******************]
[2023-12-03 18:42:06,047 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-03 18:42:06,050 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 18:42:06,050 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 18:42:06,052 : INFO : common : created directory at: artifacts]
[2023-12-03 18:42:06,052 : ERROR : main : name 'os' is not defined]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 37, in <module>
    model_trainer.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_03_training.py", line 13, in main
    prepare_callbacks_config=config.get_prepare_callback_config()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 64, in get_prepare_callback_config
    model_ckpt_dir =os.path.dirname(config.checkpoint_model_filepath)
NameError: name 'os' is not defined
[2023-12-03 18:42:57,829 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-03 18:42:57,832 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 18:42:57,833 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 18:42:57,833 : INFO : common : created directory at: artifacts]
[2023-12-03 18:42:57,833 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-03 18:42:57,834 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-03 18:43:01,716 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-03 18:43:04,946 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-03 18:43:04,946 : INFO : main : ***********************]
[2023-12-03 18:43:04,946 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-03 18:43:04,948 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 18:43:04,949 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 18:43:04,949 : INFO : common : created directory at: artifacts]
[2023-12-03 18:43:04,949 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-03 18:43:06,748 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-03 18:43:07,647 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-03 18:43:08,058 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-03 18:43:08,244 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-03 18:43:08,244 : INFO : main : ******************]
[2023-12-03 18:43:08,245 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-03 18:43:08,248 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-03 18:43:08,250 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-03 18:43:08,250 : INFO : common : created directory at: artifacts]
[2023-12-03 18:43:08,251 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-03 18:43:08,251 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-03 18:43:08,252 : INFO : common : created directory at: artifacts\training]
[2023-12-03 18:47:42,457 : INFO : main : >>>>>>>> stage Training completed <<<<<<<<<<<<<<

x========x]
[2023-12-07 20:29:56,217 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 20:29:56,219 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 20:31:00,395 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:31:00] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:31:38,833 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 18, in predict
    result=np.argmax(model.predict(test_image),axis=1)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\atanu\AppData\Local\Temp\__autograph_generated_file_a_yt_90.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)

[2023-12-07 20:31:38,836 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:31:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 20:35:53,466 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 20:35:53,466 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 20:36:01,473 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:36:01] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:36:10,605 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 19, in predict
    result=np.argmax(model.predict(test_image),axis=1)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\atanu\AppData\Local\Temp\__autograph_generated_fileqm9b_w_a.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)

[2023-12-07 20:36:10,607 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:36:10] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 20:36:24,326 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:36:24] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:49:00,925 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 20:49:00,926 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 20:49:06,536 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:49:06] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:49:21,529 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 18, in predict
    print(test_image.shape)
AttributeError: 'JpegImageFile' object has no attribute 'shape'
[2023-12-07 20:49:21,531 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:49:21] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 20:51:38,614 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 20:51:38,615 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 20:51:43,162 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:51:43] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:51:52,410 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 25, in predict
    test_image=image.load_img(imagename,target_size=(224,224))
AttributeError: 'JpegImageFile' object has no attribute 'load_img'
[2023-12-07 20:51:52,412 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:51:52] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 20:53:15,010 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 20:53:15,010 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 20:53:52,270 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:53:52] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:54:06,129 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 28, in predict
    result=np.argmax(model.predict(test_image),axis=1)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\atanu\AppData\Local\Temp\__autograph_generated_filedortw6cm.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)

[2023-12-07 20:54:06,132 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:54:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 20:55:05,204 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 20:55:05,204 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 20:55:06,386 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:55:06] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:55:06,824 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:55:06] "GET / HTTP/1.1" 200 -]
[2023-12-07 20:55:13,573 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 30, in predict
    result=np.argmax(model.predict(test_image),axis=1)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\atanu\AppData\Local\Temp\__autograph_generated_file63a21md8.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)

[2023-12-07 20:55:13,575 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:55:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 20:56:09,923 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 20:56:09] "GET / HTTP/1.1" 200 -]
[2023-12-07 21:03:07,574 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 21:03:07,574 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 21:03:10,984 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:03:10] "GET / HTTP/1.1" 200 -]
[2023-12-07 21:03:25,502 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 38, in predictionRoute
    return jsonify(result)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ndarray is not JSON serializable
[2023-12-07 21:03:25,506 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:03:25] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 21:05:27,019 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:05:27] "GET / HTTP/1.1" 200 -]
[2023-12-07 21:05:33,714 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 38, in predictionRoute
    return jsonify(result)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ndarray is not JSON serializable
[2023-12-07 21:05:33,716 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:05:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-07 21:07:41,296 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:07:41] "GET / HTTP/1.1" 200 -]
[2023-12-07 21:07:55,447 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 21:07:55,447 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 21:08:11,344 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:08:11] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:11:38,960 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:11:38] "GET / HTTP/1.1" 200 -]
[2023-12-07 21:11:45,494 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:11:45] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:11:58,625 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:11:58] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:12:30,935 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:12:30] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:12:45,019 : WARNING : def_function : 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021C4065B700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-07 21:12:45,147 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:12:45] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:15:58,128 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-07 21:15:58,129 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-07 21:16:14,526 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:16:14] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:16:26,859 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:16:26] "GET / HTTP/1.1" 200 -]
[2023-12-07 21:16:42,033 : INFO : _internal : 127.0.0.1 - - [07/Dec/2023 21:16:42] "POST /predict HTTP/1.1" 200 -]
[2023-12-07 21:19:21,677 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-07 21:19:21,679 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-07 21:19:21,681 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-07 21:19:21,682 : INFO : common : created directory at: artifacts]
[2023-12-07 21:19:21,682 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-07 21:19:21,683 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-07 21:19:25,539 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-07 21:19:27,941 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-07 21:19:27,941 : INFO : main : ***********************]
[2023-12-07 21:19:27,941 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-07 21:19:27,943 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-07 21:19:27,944 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-07 21:19:27,945 : INFO : common : created directory at: artifacts]
[2023-12-07 21:19:27,945 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-07 21:19:28,675 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-07 21:19:29,502 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-07 21:19:29,881 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-07 21:19:30,032 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-07 21:19:30,032 : INFO : main : ******************]
[2023-12-07 21:19:30,032 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-07 21:19:30,035 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-07 21:19:30,036 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-07 21:19:30,036 : INFO : common : created directory at: artifacts]
[2023-12-07 21:19:30,036 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-07 21:19:30,037 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-07 21:19:30,037 : INFO : common : created directory at: artifacts\training]
[2023-12-07 21:24:02,345 : INFO : main : >>>>>>>> stage Training completed <<<<<<<<<<<<<<

x========x]
[2023-12-09 12:53:26,649 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-09 12:53:26,653 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 12:53:26,657 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 12:53:26,657 : INFO : common : created directory at: artifacts]
[2023-12-09 12:53:26,657 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-09 12:53:26,661 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-09 12:53:33,818 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-09 12:53:38,452 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-09 12:53:38,452 : INFO : main : ***********************]
[2023-12-09 12:53:38,452 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-09 12:53:38,456 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 12:53:38,456 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 12:53:38,456 : INFO : common : created directory at: artifacts]
[2023-12-09 12:53:38,456 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-09 12:53:48,795 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-09 12:53:50,248 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-09 12:53:50,949 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-09 12:53:51,199 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-09 12:53:51,199 : INFO : main : ******************]
[2023-12-09 12:53:51,199 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-09 12:53:51,203 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 12:53:51,203 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 12:53:51,203 : INFO : common : created directory at: artifacts]
[2023-12-09 12:53:51,207 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-09 12:53:51,207 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-09 12:53:51,207 : INFO : common : created directory at: artifacts\training]
[2023-12-09 13:00:49,120 : INFO : main : >>>>>>>> stage Training completed <<<<<<<<<<<<<<

x========x]
[2023-12-09 13:02:41,336 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 13:02:41,337 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 13:02:58,393 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:02:58] "GET / HTTP/1.1" 200 -]
[2023-12-09 13:03:29,899 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:03:29] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:04:25,626 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:04:25] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:04:47,221 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:04:47] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:05:03,112 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:05:03] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:05:14,078 : WARNING : def_function : 5 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002468DA8C310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-09 13:05:14,365 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:05:14] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:05:27,226 : WARNING : def_function : 6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002468DA8C550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-09 13:05:27,512 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:05:27] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:05:39,930 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:05:39] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:05:52,105 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:05:52] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:06:29,661 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:06:29] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:06:37,787 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:06:37] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:06:51,706 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:06:51] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:07:05,086 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:07:05] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:07:15,287 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:07:15] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:07:26,304 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:07:26] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:07:37,671 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:07:37] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:07:55,085 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:07:55] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:08:02,362 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:08:02] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:08:56,980 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:08:56] "GET / HTTP/1.1" 200 -]
[2023-12-09 13:09:10,536 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:09:10] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:09:17,673 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:09:17] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:09:27,135 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:09:27] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:09:39,331 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:09:39] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:09:53,617 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:09:53] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:10:00,326 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:10:00] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:10:09,258 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 13:10:09] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 13:31:35,101 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 13:31:35,101 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 13:31:54,687 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-09 13:31:54,690 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:31:54,693 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:31:54,694 : INFO : common : created directory at: artifacts]
[2023-12-09 13:31:54,694 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-09 13:31:54,695 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-09 13:31:58,648 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-09 13:32:00,804 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-09 13:32:00,804 : INFO : main : ***********************]
[2023-12-09 13:32:00,804 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-09 13:32:00,807 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:32:00,808 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:32:00,808 : INFO : common : created directory at: artifacts]
[2023-12-09 13:32:00,809 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-09 13:32:01,577 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-09 13:32:02,429 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-09 13:32:02,818 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-09 13:32:02,959 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-09 13:32:02,959 : INFO : main : ******************]
[2023-12-09 13:32:02,960 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-09 13:32:02,962 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:32:02,963 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:32:02,964 : INFO : common : created directory at: artifacts]
[2023-12-09 13:32:02,964 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-09 13:32:02,964 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-09 13:32:02,964 : INFO : common : created directory at: artifacts\training]
[2023-12-09 13:37:48,437 : INFO : main : >>>>>>>> stage Training completed <<<<<<<<<<<<<<

x========x]
[2023-12-09 13:38:02,175 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-09 13:38:02,178 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:38:02,179 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:38:02,180 : INFO : common : created directory at: artifacts]
[2023-12-09 13:38:02,180 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-09 13:38:02,180 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-09 13:38:03,265 : INFO : data_ingestion : there is some error while extracting the files]
[2023-12-09 13:38:14,163 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-09 13:38:14,166 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:38:14,167 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:38:14,167 : INFO : common : created directory at: artifacts]
[2023-12-09 13:38:14,167 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-09 13:38:14,167 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-09 13:38:17,372 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-09 13:38:19,131 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-09 13:38:19,131 : INFO : main : ***********************]
[2023-12-09 13:38:19,131 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-09 13:38:19,134 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:38:19,136 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:38:19,136 : INFO : common : created directory at: artifacts]
[2023-12-09 13:38:19,136 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-09 13:38:19,876 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-09 13:38:20,706 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-09 13:38:21,114 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-09 13:38:21,252 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-09 13:38:21,253 : INFO : main : ******************]
[2023-12-09 13:38:21,253 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-09 13:38:21,255 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:38:21,256 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:38:21,257 : INFO : common : created directory at: artifacts]
[2023-12-09 13:38:21,257 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-09 13:38:21,257 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-09 13:38:21,257 : INFO : common : created directory at: artifacts\training]
[2023-12-09 13:39:40,278 : ERROR : main : Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].]
Traceback (most recent call last):
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\main.py", line 37, in <module>
    model_trainer.main()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\training.py", line 111, in train
    self.model.fit(
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\components\training.py", line 30, in on_epoch_end
    precision = precision_score(y_true, y_pred)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\sklearn\utils\_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\sklearn\metrics\_classification.py", line 2131, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\sklearn\utils\_param_validation.py", line 187, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\sklearn\metrics\_classification.py", line 1724, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\sklearn\metrics\_classification.py", line 1518, in _check_set_wise_labels
    raise ValueError(
ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
[2023-12-09 13:43:16,497 : INFO : main : >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-09 13:43:16,500 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:43:16,501 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:43:16,502 : INFO : common : created directory at: artifacts]
[2023-12-09 13:43:16,502 : INFO : common : created directory at: artifacts/data_ingestion]
[2023-12-09 13:43:16,502 : INFO : data_ingestion : The file is already exists of size :]
[2023-12-09 13:43:19,698 : INFO : data_ingestion : file has been successfully exxtracted .]
[2023-12-09 13:43:21,670 : INFO : main : >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-09 13:43:21,671 : INFO : main : ***********************]
[2023-12-09 13:43:21,671 : INFO : main : >>>>>>>>>>> Stage Prepare base model started <<<<<<<<<<<]
[2023-12-09 13:43:21,673 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:43:21,674 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:43:21,674 : INFO : common : created directory at: artifacts]
[2023-12-09 13:43:21,674 : INFO : common : created directory at: artifacts/prepare_base_model]
[2023-12-09 13:43:22,429 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-09 13:43:23,227 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2023-12-09 13:43:23,630 : INFO : builder_impl : Assets written to: artifacts\prepare_base_model\assets]
[2023-12-09 13:43:23,789 : INFO : main : >>>>>>>>>>>> stage Prepare base model ,completed <<<<<<<<<<

X=================X]
[2023-12-09 13:43:23,789 : INFO : main : ******************]
[2023-12-09 13:43:23,789 : INFO : main : >>>>>>>> stage Training started <<<<<<<]
[2023-12-09 13:43:23,791 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2023-12-09 13:43:23,792 : INFO : common : yaml file: params.yaml loaded successfully]
[2023-12-09 13:43:23,793 : INFO : common : created directory at: artifacts]
[2023-12-09 13:43:23,793 : INFO : common : created directory at: \artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-09 13:43:23,793 : INFO : common : created directory at: \artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-09 13:43:23,794 : INFO : common : created directory at: artifacts\training]
[2023-12-09 13:49:11,385 : INFO : main : >>>>>>>> stage Training completed <<<<<<<<<<<<<<

x========x]
[2023-12-09 13:49:46,572 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 13:49:46,573 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 15:12:25,073 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 15:12:25,073 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 15:12:38,477 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:12:38] "GET / HTTP/1.1" 200 -]
[2023-12-09 15:12:53,165 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:12:53] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:13:07,002 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:13:07] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:13:22,706 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:13:22] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:14:54,012 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 15:14:54,012 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 15:15:07,357 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 23, in predict
    test_image = image.img_to_array(test_image)
UnboundLocalError: local variable 'test_image' referenced before assignment
[2023-12-09 15:15:07,360 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:15:07] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-09 15:15:50,830 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 15:15:50,830 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 15:15:57,676 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:15:57] "GET / HTTP/1.1" 200 -]
[2023-12-09 15:16:04,202 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 23, in predict
    test_image = image.img_to_array(imagename)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\keras\utils\image_utils.py", line 324, in img_to_array
    x = np.asarray(img, dtype=dtype)
ValueError: could not convert string to float: 'inputImage.jpg'
[2023-12-09 15:16:04,205 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:16:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-09 15:17:01,196 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 15:17:01,197 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 15:17:07,242 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:17:07] "GET / HTTP/1.1" 200 -]
[2023-12-09 15:17:13,774 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\atanu\anaconda3\envs\chicken\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\atanu\Desktop\MY_WORK\mlops\chicken_disease_classification\app.py", line 37, in predictionRoute
    result=clApp.classifier.predict()
  File "c:\users\atanu\desktop\my_work\mlops\chicken_disease_classification\src\cnnClassifier\pipeline\predict.py", line 26, in predict
    test_image=test_image.reshape((224,224))
ValueError: cannot reshape array of size 150528 into shape (224,224)
[2023-12-09 15:17:13,775 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:17:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-09 15:19:26,243 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2023-12-09 15:19:26,243 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2023-12-09 15:19:29,902 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:19:29] "GET / HTTP/1.1" 200 -]
[2023-12-09 15:19:40,543 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:19:40] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:19:50,270 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:19:50] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:19:59,786 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:19:59] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:20:08,183 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:20:08] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:20:20,022 : WARNING : def_function : 5 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021B8A22B160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-09 15:20:20,310 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:20:20] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:20:26,544 : WARNING : def_function : 6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021B8A1F1790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-12-09 15:20:26,779 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:20:26] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:20:35,375 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:20:35] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:20:46,173 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:20:46] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:20:54,880 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:20:54] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:01,316 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:01] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:08,091 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:08] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:18,304 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:18] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:25,759 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:25] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:33,095 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:33] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:40,672 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:40] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:47,952 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:47] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:21:58,749 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:21:58] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:22:05,950 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:22:05] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:22:15,346 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:22:15] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:22:25,845 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:22:25] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:22:32,659 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:22:32] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:22:59,531 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:22:59] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:23:07,079 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:23:07] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:23:15,405 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:23:15] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:23:24,103 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:23:24] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:23:34,837 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:23:34] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:23:41,825 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:23:41] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:23:55,652 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:23:55] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:24:16,112 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:24:16] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:24:28,909 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:24:28] "POST /predict HTTP/1.1" 200 -]
[2023-12-09 15:24:49,412 : INFO : _internal : 127.0.0.1 - - [09/Dec/2023 15:24:49] "POST /predict HTTP/1.1" 200 -]
